language: go

# Only the last two Go releases are supported by the Go team with security
# updates. Any versions older than that should be considered deprecated.
# Don't bother testing with them. tip builds your code with the latest
# development version of Go. This can warn you that your code will break
# in the next version of Go. Don't worry! Later we declare that test runs
# are allowed to fail on Go tip.
go:
  - "1.10"
  - master

# Skip the install step. Don't `go get` dependencies. Only build with the
# code in vendor/
install: true

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

# Don't email me the results of the test runs.
notifications:
  email: false

git:
  depth: 1

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - GOLANGCI_LINT_VERSION="v1.10.2"
  - go get -v github.com/Masterminds/glide
  - go get -u golang.org/x/lint/golint
#  - go get honnef.co/go/tools/cmd/megacheck
#  - go get github.com/fzipp/gocyclo
#  - go get golang.org/x/tools/cmd/goimports
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}

script:
  - glide install
  - golangci-lint run -E goimports -D errcheck --skip-dirs vendor
#  - test -z "$(goimports -d $(find . -type f -name '*.go' -not -path './vendor/*'))" # Fail if a .go file hasn't been formatted with gofmt
#  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
#  - megacheck ./...                          # "go vet on steroids" + linter
# TODO: Uncomment this:
# Temporary disable linters to get build working for now.
#  - gocyclo -over 19 $GO_FILES               # forbid code with huge functions
#  - golint -set_exit_status $(go list ./...) # one last linter
