language: go
go:
  - "1.11"
install: true
notifications:
  email: false
git:
  depth: 1
before_script:
  - go get -v github.com/Masterminds/glide
  - GOLANGCI_LINT_VERSION="v1.10.2"
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin ${GOLANGCI_LINT_VERSION}
script:
  - make go/ci/check
